### Log level
logging:
  level:
    org.springframework: DEBUG

#### Default server port #########
server:
  port: 9000

# config the DataSource:
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 50000

#Tell Mybatis that where the object-table-mapping files (mapper.xml) are.
mybatis-plus:
# See the Doc of Interface com.baomidou.mybatisplus.core.mapper.BaseMapper<T> extends Mapper<T>
# Mapper 继承该 BaseMapper 接口后，无需编写 mapper.xml 文件，即可获得CRUD功能,即不需要mapper-locations配置了。mapper.xml已经打成了 zip 包
# mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto #primary key increases automatically for ALL TABLES


