server:
  port: 88

logging:
  level:
    org.springframework: DEBUG

spring:
  cloud:
    gateway:
      routes: #command + Mouse-left 点进去能发现 routes 的值是一个List
        #定义一个最简单的 route
        - id: route_baidu #每一个路由都应该有一个 id, 或者称为名字
          predicates: #(predicates在这里应翻译为'断言'，而不是'谓词')
            - Path=/baidu #判断如果请求路径 中是否包含 "/baidu"字样 如 localhost:88/baidu 这个请求就会被匹配为 true
          filters: #(Filter chain 过滤器链)如果断言结果为 true ，则依次执行如下 filter
            - AddRequestParameter=ie, utf-8
            - AddRequestParameter=wd, hello
            - RemoveRequestParameter
          uri: https://www.baidu.com  #原始请求经过一系列 filters 之后会被发送给这个目标 uri 。

        #可以定义多个 route, 再定义另一个 route
        - id: route_qq
          predicates:
            - Path=/jianshu
          filters:
            - AddRequestParameter=q, hi
          uri: https://www.jianshu.com/search
